filebeat.prospectors:
- type: log
  paths:
    - 

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://localhost:5601
  username: elastic
  password: changeme

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  username: elastic
  password: changeme
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
